# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: pmd

on:
  push:
    branches: [ apex, java ]
  #pull_request:
  #  branches: [ apex, java ]
  workflow_dispatch:

jobs:
  pmd-code-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run PMD (Java)
        if: ${{ github.ref_name == 'java' }}
        uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'rulesets/java/quickstart.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false
      - name: Run PMD (Apex)
        if: ${{ github.ref_name == 'apex' }}
        uses: pmd/pmd-github-action@v1
        #uses: pmd/pmd-github-action@main
        with:
          rulesets: 'rulesets/apex/quickstart.xml'
          sourcePath: 'src/classes'
          analyzeModifiedFilesOnly: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pmd-report.sarif
