name: Salesforce Apex Code Review

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  apex-code-review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Salesforce CLI
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir -p sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install
        echo "./sfdx-cli/bin" >> $GITHUB_PATH

    - name: Install PMD
      run: |
        wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.41.0/pmd-bin-6.41.0.zip
        unzip pmd-bin-6.41.0.zip
        echo "$PWD/pmd-bin-6.41.0/bin" >> $GITHUB_PATH

    - name: Run PMD Apex Code Analysis
      run: |
        pmd pmd -d ./force-app/main/default/classes -R category/apex/design.xml -f text

    # Agrega pasos adicionales según sea necesario para tu flujo de trabajo
